### ISSUE TITLE
Add feature to skip the condor_vault_storer portion to token-push

### ISSUE THREAD

**Issue by shreyb** [fermitools/managed-tokens#72]
This is basically to speed up token pushing in the case that we had a service's refresh token expire and we just regenerated it using `run-onboarding-managed-tokens`. 

In this case, we should do the following:

1. Have flag (--skip-vault-store) to skip the condor_vault_storer step to token-push
2. However, this relies on vault tokens being stored on disk correctly.  We need to figure out a way to make sure that a valid state exists where a vault token can be pushed.  Maybe check for existence of file where we expect it before we even try anything?
3. Then proceed with kinit and push steps

**Comment by retzkek** [comment]
Can `run-onboarding-managed-tokens` run the push step itself, instead of having the user do that manually?

**Comment by shreyb** [comment]
Yeah - I think that's reasonable.

**Comment by shreyb** [comment]
It occurred to me while looking at this again that since there's a lot of overlap between what this was intended to do, what @retzkek suggested, and what `token-push` now does.  It might be cleaner to do away with the `run-onboarding-managed-tokens` altogether, since that currently just does the first two operations of `token-push` (gets kerberos ticket, `condor_vault_storer`, the latter in interactive mode) and doesn't do the notifications that `token-push` does.

The revised `token-push` might have the following:
* A flag `--run-onboarding` that makes `token-push` imitate the current behavior of `run-onboarding-managed-tokens`, by checking for only one service given (`--service` has to be called too), and ensuring that notifications are disabled (`disableNotifications = true`).  Then it could exit after running the `condor_vault_storer` interactively, unless....
* ...A second flag `--push-tokens` is set.  This flag would be ignored unless `--run-onboarding` was set, since it's redundant in the standard `token-push` case.  If both of these flags are set, the only difference between this and the standard token-push case is that `--service` MUST be set, and the `condor_vault_storer` (`vaultTokenStoreWorker`) would run interactively.  

Hopefully, this will also allow for the package `internal/cmdUtils` to shrink, since a lot of the code there is shared between `token-push` and `run-onboarding-managed-tokens`, and would thus move to the folder of `token-push`.

**Comment by shreyb** [comment]
I'm starting to get this mocked out now.  I have the `--run-onboarding` and `--push-tokens` flag done, and I noticed some cleanup actions I want to take before opening a PR for this.

**Comment by shreyb** [comment]
The work on this is finished, and passes all unit tests and manual testing with different configuration files.  

# High-level changes

* Removed `run-onboarding-managed-tokens` executable, and merged its capabilities into `token-push` via the flag `-r/--run-onboarding`.  As @retzkek suggested, there is now the option to use an additional flag `-p/--push-tokens` that will push the vault tokens to interactive nodes, so the onboarding and first push can be done in a single step.
* Removed `internal/cmdUtils` package.  Almost all of this package was funcs and types shared between `token-push` and `run-onboarding-managed-tokens`.  Since the latter is now gone, I could move most of `cmdUtils` into the `token-push` `package main`.  The very few things that are needed by both `token-push` and `refresh-uids-from-ferry` are simply duplicated.
* According to best practices, moved interfaces out of/unexported interfaces from implementing packages into consuming packages (e.g. `vaultToken` --> `worker`, `worker` --> `main`, etc.)
* Other general code cleanup for better readability/usability

# Details

## Removed `run-onboarding-managed-tokens` executable

The `run-onboarding-managed-tokens` executable now has been merged into the `token-push` executable, accessible by a flag `-r/--run-onboarding`.  When the `-r` flag is used, the `-s` flag with a `<SERVICE>` argument must also be specified, like:

```
$ token-push --run-onboarding -s my_service
```

`token-push` will exit with an error if the `-s` flag is not specified in this case.

To push tokens after the initial onboarding, all in one step, the `-p/--push-tokens` flag can be used.  This functionality was kept opt-in rather than default in case the destination nodes for a service were not available at the time of onboarding.  Doing all of the onboarding steps at once would look like:

```
$ token-push --run-onboarding -s my_service --push-tokens
```

The two executables here had nearly the same setup actions and first two steps (initializing Kerberos credentials, and then running condor_vault_storer), but the difference was merely that the second step needs to wait for the user for `run-onboarding-managed-tokens`, and shouldn't for `token-push`.  In the new merged `token-push`, there is a simple switch that chooses which mode that second step is run in (technically, which `internal/worker.workerFunc` is chosen to start up in a goroutine).

##  Removed `internal/cmdUtils` package

As mentioned in the high-level summary, most of this package was for the common funcs and types shared between `token-push` and `run-onboarding-managed-tokens`.  Most of this package was moved into various files in the `token-push` `main` package.   This also allowed me the ability to unexport a number of functions that were formerly exported in `internal/cmdUtils`.

The only types and functions that had to be duplicated between `token-push` and `refresh-uids-from-ferry` are the `disableNotificationsOption` type and its associated methods and functions.

## Moved interfaces out of/unexported interfaces from implementing packages into consuming packages

This was motivated by trying to simplify the code base.  There were many interfaces that were really serving no purpose where they were.  Some, like `internal/worker.ChannelsForWorkers`, were needlessly complicating the code where they were, and so were moved to the packages where those interfaces could be useful - in this case, to the `token-push` `main` package (as `chansForWorkers`).  Others, like `internal/vaultToken.TokenStorer`, weren't serving any real purpose being exported, and ones like that were unexported, with exported wrapper functions being provided to fill any functionality gap (`vaultToken.StoreAndValidateToken` was repurposed for this, for example).

## General code cleanup

Discussions with my colleagues and my own troubleshooting made me realize that some of the code was needlessly complicated.  

One big example of this was the `internal/worker.StoreAndGetTokenWorker` func, which prepared a slice of functions - one per schedd - essentially, and then fed those into a func `worker.StoreAndGetTokensForSchedds` that operated on the slice.  @stlammel mentioned to me while perusing the code for another purpose that he wasn't able to find the schedd loop, and he's right - it wasn't obvious that we were looping over the schedds and doing a specific operation for each (`condor_vault_storer`), because the code before had this split into two funcs.  Now, the schedd loop is handled inside the `worker.workerFunc` definition, and the lower-level funcs only deal with one schedd, which greatly simplifies reading the code.

Another example of overcomplication was how `token-push` generated the `worker.Config` objects and stored them at the beginning of the run.  Up through version v0.15.0, this was accomplished by starting up a separate goroutine to control access to two maps: `serviceConfigs` and `successfulServices`.  This original implementation necessitated two semaphore channels and two data channels to synchronize the generation of the `Config`s, and the population of the two previously-mentioned maps.  This was definitely overkill.   Since each `Config` is generated in its own goroutine, and _that_ operation is where concurrency really helps, I simplified the population of the `serviceConfigs` and `successfulServices` by simply having access to each mediated by a `sync.Mutex`.  This greatly reduced the complexity of the code, and I was able to do away with all five extra channels that previously synchronized this.

# Tests Run
* Unit tests
* Manual tests (mediated by different test configuration files) - All passed:
  * General config file with both valid and invalid configuration values
  * Config that forced all errors to be sent
  * Config with a bad collector value, so schedd obtaining would fail
  * Config with only invalid values
  * Config where we disable all notifications
  * Config where only one service has notifications disabled (globally: `disableNotifications = false`, for one service, `disableNotificationsOverride = true`)
  * Configuration where some services had notifications disabled, others did not
  * Configuration with an invalid primary collector value, valid secondary value to test collector fallback
  * Configuration where we force IPv4 connections
  * Configuration where we force certain operations to timeout by setting very short timeouts
