### ISSUE TITLE
Make IPv4/IPv6 configurable

### ISSUE THREAD

**Issue by shreyb** [fermitools/managed-tokens#80]
We've had some network issues on our production machine recently, and the workaround has been to set the ssh config to use IPv4. 

We should move this into the configuration so that we mirror the ssh_config setting and say `AddressFamily: {inet, inet6, any}` and use that to drive adding a `-4` or a `-6` or nothing respectively to the pingOptions and fileCopier options.

This is semi-urgent, so it should be done before any other feature-requests.

**Comment by marcmengel** [comment]
Note that we *could* just bury that in the .ssh/config and consider that part of the overall (managed) configuration, thus simplifying the managed-tokens code;
OR
 we could include custom .ssh/config lines in the main configuration as a way of supporting things like forwarding through other hosts, limiting to ipv4, or logging in as particular users; I.e. anything that the sshd.config supports.   Then the .ssh/config would be generated from a stock prefix and these custom entries per host.

**Comment by shreyb** [comment]
Yep - so I've added those to the .ssh/config already to get the service working for most of the nodes (though that doesn't affect the part of the code that pings the nodes to make sure they're up.  This issue addresses that case too).

The way we handle rsync currently is we allow for options to be specified in configuration, and then provide a default set of options that just get pre-pended to the rsync command.  I was thinking of doing the same here.  I _think_ this is just a matter of adding an extra argument to a few functions.

If possible, since this is deployed on a catch-all machine, I'd rather not have to touch the .ssh/config as much as possible (though I understand that right now it's needed for tunneling).  I figure that as much as we can put into the application config, while providing sensible defaults, would keep operations simpler.

**Comment by shreyb** [comment]
Done for SSH options.  I want to review the rsync options and then I'll be ready to test/deploy this.

**Comment by shreyb** [comment]
Done for rsync options.  We already had the capability for the rsync options, but I changed it so that rsync, ssh, and ping look very similar in how they're passed.

Will test on Monday and perhaps deploy.

**Comment by shreyb** [comment]
Tests look good.

Example of `ping` logged statement with the `-4` passed in correctly:
```
DEBU[0008] Running command to ping node                  command="/usr/bin/ping -W 5 -c 1 -4 hostname" node=hostname
```

Copy/pasting that same command to our production machine to test connecting to a problematic host:

```
$ /usr/bin/ping -W 5 -c 1  problematic-host
PING <hostinfo> 56 data bytes
From <local host> icmp_seq=1 Destination unreachable: Address unreachable

--- <problematic-host> ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

# With command pasted from debug log
$ /usr/bin/ping -W 5 -c 1 -4 problematic-host
PING  <problematic-host> 56(84) bytes of data.
64 bytes from <problematic-host-info-with-ipv4-address>: icmp_seq=1 ttl=63 time=0.254 ms

---  ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.254/0.254/0.254/0.000 ms
```

Similarly, for the `rsync` command the `fileCopier` code runs, we want to pass in `-o AddressFamily=inet`.  Here is the debug output that prints the underlying rsync command:
```
/usr/bin/rsync -e /usr/bin/ssh -o ConnectTimeout=30 -o ServerAliveCountMax=1 -o ServerAliveInterval=30 -o AddressFamily=inet --perms --chmod=u=r,go= <source_token_file> <account>@<hostname>:/path/to/destination/token
```

So this is good to go.
